name: Create community release post
on:
  # @PERCONA - disable workflow
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Get vault secrets"
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          # Secrets placed in the ci/repo/grafana/grafana/community_release path in Vault
          repo_secrets: |
            GRAFANABOT_FORUM_KEY=community_release:GRAFANABOT_FORUM_KEY

      - name: Run community-release (manually invoked)
        uses: grafana/grafana-github-actions-go/community-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          community_api_key: ${{ env.GRAFANABOT_FORUM_KEY }}
          community_api_username: grafanabot
          dry_run: ${{ inputs.dry_run }}
