name: Crowdin automatic task management

on:
  # @PERCONA - disable workflow
  workflow_dispatch:
jobs:
  create-tasks-in-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-create-tasks.yml@main
    with:
      crowdin_project_id: 5
