name: Crowdin Upload Action

on:
  # @PERCONA - disable workflow
  workflow_dispatch:
jobs:
  upload-sources-to-crowdin:
    if: github.repository == 'grafana/grafana'
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-upload.yml@main
    with:
      crowdin_project_id: 5
